# -*- coding: utf-8 -*-
"""Predictive Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eenFG_bpXUhLZ7LUOJ4UcydQfNXZoSVf
"""

S!pip install prophet --quiet
!pip install statsmodels --quiet

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.seasonal import seasonal_decompose
from prophet import Prophet

import warnings
warnings.filterwarnings('ignore')

from google.colab import files
uploaded = files.upload()

import io

df = pd.read_csv('AirPassengers.csv')

print("Original column names :", df.columns.tolist())
print()

df.rename(columns={'#Passengers': 'Passengers'}, inplace=True)

df['Month'] = pd.to_datetime(df['Month'], format='%Y-%m')

df.set_index('Month', inplace=True)

print("Column names after fixing:", df.columns.tolist())
print()
print("First 5 rows of your data:")
print(df.head())
print()
print("Last 5 rows of your data:")
print(df.tail())

print(" COMPLETE DATA ANALYSIS REPORT")

print("\n1. SIZE OF THE DATASET")
print(f"   Total months of data : {len(df)}")
print(f"   Total columns        : {df.shape[1]}")

print("\n2. DATE RANGE")
print(f"   Starting from : {df.index.min().strftime('%B %Y')}")
print(f"   Ending at     : {df.index.max().strftime('%B %Y')}")
print(f"   Total years   : {df.index.max().year - df.index.min().year + 1} years")

print("\n3. PASSENGER STATISTICS")
print(f"   Minimum passengers : {df['#Passengers'].min()}  (lowest month)")
print(f"   Maximum passengers : {df['#Passengers'].max()}  (highest month)")
print(f"   Average passengers : {df['#Passengers'].mean():.1f}")
print(f"   Median passengers  : {df['#Passengers'].median():.1f}")

print("\n4. MISSING VALUES CHECK")
missing = df['#Passengers'].isnull().sum()
print(f"   Missing values : {missing}  {'(No missing values - perfect!)' if missing == 0 else '(We need to fix this!)'}")

print("\n5. YEAR WITH HIGHEST PASSENGERS")
df_temp = df.copy()
df_temp['Year'] = df_temp.index.year
yearly = df_temp.groupby('Year')['#Passengers'].sum()
best_year = yearly.idxmax()
print(f"   Year {best_year} had the most total passengers: {yearly[best_year]}")

print("\n6. MONTH WITH HIGHEST PASSENGERS ON AVERAGE")
df_temp['MonthName'] = df.index.strftime('%B')
monthly_avg = df_temp.groupby('MonthName')['#Passengers'].mean().round(1)
best_month = monthly_avg.idxmax()
print(f"{best_month} is the busiest month on average with {monthly_avg[best_month]} passengers")

print("\n7. FULL DATA TABLE")
print(df)

plt.figure(figsize=(14, 5))


plt.plot(df.index, df['Passengers'],
         color='steelblue', linewidth=2.5, label='Monthly Passengers')

plt.fill_between(df.index, df['Passengers'], alpha=0.15, color='steelblue')

max_idx = df['Passengers'].idxmax()
max_val = df['Passengers'].max()
plt.annotate(f'Highest: {max_val}',
             xy=(max_idx, max_val),
             xytext=(max_idx, max_val + 30),
             arrowprops=dict(arrowstyle='->', color='red'),
             color='red', fontsize=10)

min_idx = df['Passengers'].idxmin()
min_val = df['Passengers'].min()
plt.annotate(f'Lowest: {min_val}',
             xy=(min_idx, min_val),
             xytext=(min_idx, min_val - 50),
             arrowprops=dict(arrowstyle='->', color='darkgreen'),
             color='darkgreen', fontsize=10)

plt.title('Air Passengers from 1949 to 1960 — Historical Data', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Number of Passengers (thousands)', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

df_copy = df.copy()
df_copy['Year']  = df_copy.index.year
df_copy['MonthNum'] = df_copy.index.month


yearly_total   = df_copy.groupby('Year')['Passengers'].sum()
monthly_avg    = df_copy.groupby('MonthNum')['Passengers'].mean()

month_names = ['Jan','Feb','Mar','Apr','May','Jun',
               'Jul','Aug','Sep','Oct','Nov','Dec']

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ---Yearly Growth ---
axes[0].bar(yearly_total.index, yearly_total.values,
            color='steelblue', edgecolor='white', linewidth=0.5)
axes[0].set_title('Total Passengers Per Year', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Year')
axes[0].set_ylabel('Total Passengers')
axes[0].grid(True, alpha=0.3, axis='y')


for year, val in yearly_total.items():
    axes[0].text(year, val + 20, str(val), ha='center', fontsize=8, color='navy')

# --- Monthly Average ---
bars = axes[1].bar(range(1, 13), monthly_avg.values,
                   color='coral', edgecolor='white', linewidth=0.5)
axes[1].set_title('Average Passengers by Month (Seasonal Pattern)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Month')
axes[1].set_ylabel('Average Passengers')
axes[1].set_xticks(range(1, 13))
axes[1].set_xticklabels(month_names)
axes[1].grid(True, alpha=0.3, axis='y')

# Highlight July and August
bars[6].set_color('crimson')
bars[7].set_color('crimson')

plt.tight_layout()
plt.show()

print("July and August (red bars) are clearly the busiest months every year!")
print("Passengers grew from", yearly_total[1949], "total in 1949 to", yearly_total[1960], "total in 1960")

result = seasonal_decompose(df['Passengers'], model='multiplicative', period=12)
fig, axes = plt.subplots(4, 1, figsize=(14, 12))

# --- Original Data ---
axes[0].plot(result.observed, color='steelblue', linewidth=1.5)
axes[0].set_ylabel('Original Data', fontsize=11)
axes[0].set_title('Seasonal Decomposition of Your AirPassengers Data', fontsize=14, fontweight='bold')
axes[0].grid(True, alpha=0.3)

# --- Trend ---
axes[1].plot(result.trend, color='orange', linewidth=2.5)
axes[1].set_ylabel('Trend', fontsize=11)
axes[1].set_title('Trend', fontsize=11)
axes[1].grid(True, alpha=0.3)

# --- Seasonality ---
axes[2].plot(result.seasonal, color='green', linewidth=1.5)
axes[2].set_ylabel('Seasonal', fontsize=11)
axes[2].set_title('Seasonality', fontsize=11)
axes[2].grid(True, alpha=0.3)

# --- Residual ---
axes[3].plot(result.resid, color='red', linewidth=1, marker='o', markersize=3)
axes[3].set_ylabel('Residual', fontsize=11)
axes[3].set_title('Residual', fontsize=11)
axes[3].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

df_ml = df.reset_index()
df_ml.columns = ['Month', 'Passengers']

df_ml['Year']        = df_ml['Month'].dt.year
df_ml['MonthNum']    = df_ml['Month'].dt.month
df_ml['TimeIndex']   = range(len(df_ml))

df_ml['Lag_1']       = df_ml['Passengers'].shift(1)
df_ml['Lag_12']      = df_ml['Passengers'].shift(12)
df_ml['Rolling_3']   = df_ml['Passengers'].rolling(3).mean()

df_ml = df_ml.dropna().reset_index(drop=True)

features = ['TimeIndex', 'Year', 'MonthNum', 'Lag_1', 'Lag_12', 'Rolling_3']
X = df_ml[features]
y = df_ml['Passengers']


split_point = int(len(X) * 0.8)

X_train = X[:split_point]
X_test  = X[split_point:]
y_train = y[:split_point]
y_test  = y[split_point:]

print("Data prepared for Machine Learning!")
print()
print(f"Total rows after cleaning : {len(df_ml)}")
print(f"Training rows (80%)       : {len(X_train)}")
print(f"Testing rows  (20%)       : {len(X_test)}")
print()
print("Features being used:")
for f in features:
    print(f"- {f}")
print()
print("Sample of prepared data:")
print(df_ml[['Month', 'Passengers', 'Lag_1', 'Lag_12', 'Rolling_3']].head(8).to_string(index=False))

#LINEAR REGRESSION
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
print("Linear Regression model trained!")

lr_pred = lr_model.predict(X_test)
lr_mae  = mean_absolute_error(y_test, lr_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
lr_r2   = r2_score(y_test, lr_pred)

print()
print("ACCURACY RESULTS")
print(f" MAE  (Mean Absolute Error)  : {lr_mae:.2f}")
print(f" RMSE (Root Mean Sq. Error)  : {lr_rmse:.2f}")
print(f" R2 Score                    : {lr_r2:.4f}")
print()
print(f" On average, predictions are off by {lr_mae:.1f} passengers")
print(f"R2 of {lr_r2:.2f} means the model explains {lr_r2*100:.1f}% of the variation")
print()

test_dates = df_ml['Month'].iloc[split_point:]

plt.figure(figsize=(12, 4))
plt.plot(test_dates, y_test.values, color='steelblue', linewidth=2, label='Actual Passengers')
plt.plot(test_dates, lr_pred,       color='red',       linewidth=2,
         linestyle='--', label='Linear Regression Prediction')
plt.title('Linear Regression — Actual vs Predicted', fontsize=13, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Passengers')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# RANDOM FOREST
rf_model = RandomForestRegressor(n_estimators=200, random_state=42)

rf_model.fit(X_train, y_train)
print("Random Forest model trained with 200 trees!")

rf_pred = rf_model.predict(X_test)

rf_mae  = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2   = r2_score(y_test, rf_pred)

print()
print(" ACCURACY RESULTS")
print(f" MAE  (Mean Absolute Error)  : {rf_mae:.2f}")
print(f" RMSE (Root Mean Sq. Error)  : {rf_rmse:.2f}")
print(f" R2 Score                    : {rf_r2:.4f}")
print()
imp = pd.DataFrame({'Feature': features,
                    'Importance': rf_model.feature_importances_}
                  ).sort_values('Importance', ascending=False)

print("  Which features helped the model the most:")
for _, row in imp.iterrows():
    bar = '█' * int(row['Importance'] * 50)
    print(f"  {row['Feature']:<15} {bar}  {row['Importance']:.4f}")


test_dates = df_ml['Month'].iloc[split_point:]

plt.figure(figsize=(12, 4))
plt.plot(test_dates, y_test.values, color='steelblue', linewidth=2, label='Actual Passengers')
plt.plot(test_dates, rf_pred,       color='green',     linewidth=2,
         linestyle='--', label='Random Forest Prediction')
plt.title('Random Forest — Actual vs Predicted', fontsize=13, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Passengers')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ARIMA
train_ts = df['Passengers'][:-24]
test_ts  = df['Passengers'][-24:]

print(f"Training ARIMA on {len(train_ts)} months (1949-01 to 1957-12)")
print(f"Testing on last {len(test_ts)} months (1958-01 to 1960-12)")


arima_model = ARIMA(train_ts, order=(5, 1, 0))
arima_fit   = arima_model.fit()
print("ARIMA model trained!")

arima_pred = arima_fit.forecast(steps=24)

arima_mae  = mean_absolute_error(test_ts, arima_pred)
arima_rmse = np.sqrt(mean_squared_error(test_ts, arima_pred))

print()

print("ACCURACY RESULTS")

print(f"  MAE  (Mean Absolute Error)  : {arima_mae:.2f}")
print(f"  RMSE (Root Mean Sq. Error)  : {arima_rmse:.2f}")
print()

plt.figure(figsize=(12, 4))
plt.plot(train_ts.index, train_ts.values, color='steelblue', linewidth=2, label='Training Data')
plt.plot(test_ts.index,  test_ts.values,  color='green',     linewidth=2, label='Actual (Test)')
plt.plot(test_ts.index,  arima_pred.values, color='red',     linewidth=2,
         linestyle='--', label='ARIMA Forecast')
plt.axvline(test_ts.index[0], color='gray', linestyle=':', label='Train/Test Split')
plt.title('ARIMA — Actual vs Forecasted (Last 24 Months)', fontsize=13, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Passengers')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

df_prophet = df.reset_index()
df_prophet.columns = ['ds', 'y']

print("Data formatted for Prophet:")
print(df_prophet.head(5).to_string(index=False))

prophet_model = Prophet(
    yearly_seasonality  = True,
    weekly_seasonality  = False,
    daily_seasonality   = False,
    seasonality_mode    = 'multiplicative'
)
prophet_model.fit(df_prophet)
print()
print("Prophet model trained successfully!")

future = prophet_model.make_future_dataframe(periods=36, freq='MS')
print(f"Forecasting from {df_prophet['ds'].min().date()} to {future['ds'].max().date()}")

prophet_forecast = prophet_model.predict(future)

print()
print("Future predictions (last 12 months of forecast):")
future_only = prophet_forecast[prophet_forecast['ds'] > df_prophet['ds'].max()]
print(future_only[['ds','yhat','yhat_lower','yhat_upper']].tail(12).round(1).to_string(index=False))

fig, axes = plt.subplots(2, 1, figsize=(14, 11))


axes[0].plot(df_prophet['ds'], df_prophet['y'],
             color='steelblue', linewidth=2.5, label='Actual Data (1949–1960)')


axes[0].plot(prophet_forecast['ds'], prophet_forecast['yhat'],
             color='crimson', linewidth=2, linestyle='--', label='Prophet Forecast')


axes[0].fill_between(prophet_forecast['ds'],
                     prophet_forecast['yhat_lower'],
                     prophet_forecast['yhat_upper'],
                     alpha=0.2, color='crimson', label='Confidence Interval (likely range)')


axes[0].axvline(df_prophet['ds'].max(), color='gray',
                linestyle=':', linewidth=2, label='Forecast Starts Here')

axes[0].set_title('Prophet Forecast — 3 Years Into the Future (1961–1963)',
                  fontsize=14, fontweight='bold')
axes[0].set_ylabel('Number of Passengers', fontsize=12)
axes[0].set_xlabel('Year', fontsize=12)
axes[0].legend(loc='upper left')
axes[0].grid(True, alpha=0.3)

seasonal = prophet_forecast[['ds', 'yearly']].dropna()

axes[1].plot(seasonal['ds'], seasonal['yearly'],
             color='green', linewidth=2)
axes[1].fill_between(seasonal['ds'], seasonal['yearly'],
                     alpha=0.15, color='green')
axes[1].axhline(0, color='gray', linestyle='--', linewidth=1)
axes[1].set_title('Yearly Seasonal Pattern — Summer Peaks, Winter Dips',
                  fontsize=13, fontweight='bold')
axes[1].set_ylabel('Seasonal Effect', fontsize=12)
axes[1].set_xlabel('Year', fontsize=12)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("The model has learned the seasonal pattern and extended it into the future.")
print("Passengers are predicted to continue growing every year.")

print("FINAL MODEL COMPARISON REPORT")
print()
print(f"  {'Model':<25} {'MAE':>8} {'RMSE':>10}  {'R2':>8}")
print("  " + "-" * 55)
print(f"  {'Linear Regression':<25} {lr_mae:>8.2f} {lr_rmse:>10.2f}  {lr_r2:>8.4f}")
print(f"  {'Random Forest':<25} {rf_mae:>8.2f} {rf_rmse:>10.2f}  {rf_r2:>8.4f}")
print(f"  {'ARIMA':<25} {arima_mae:>8.2f} {arima_rmse:>10.2f}  {'N/A':>8}")
print(f"  {'Prophet':<25} {'Best visual result — see chart above':>35}")
print()

scores = {
    'Linear Regression': lr_mae,
    'Random Forest'    : rf_mae,
    'ARIMA'            : arima_mae
}
best_model = min(scores, key=scores.get)
print(f"  Best model by MAE score : {best_model}")
print()
print("  LEGEND:")
print("  MAE  = Average error in passenger predictions (lower = better)")
print("  RMSE = Punishes large errors more (lower = better)")
print("  R2   = % of pattern explained by model (higher = better, max = 1.0)")

fig, ax = plt.subplots(figsize=(9, 4))
model_names = ['Linear Regression', 'Random Forest', 'ARIMA']
mae_values  = [lr_mae, rf_mae, arima_mae]
colors      = ['steelblue', 'green', 'orange']

bars = ax.bar(model_names, mae_values, color=colors, edgecolor='white', linewidth=0.8, width=0.5)

for bar, val in zip(bars, mae_values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
            f'{val:.2f}', ha='center', fontsize=12, fontweight='bold')

ax.set_title('Model Comparison — MAE Score (Lower Bar = Better Model)',
             fontsize=13, fontweight='bold')
ax.set_ylabel('Mean Absolute Error (MAE)', fontsize=11)
ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

output = prophet_forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()
output.columns = ['Date', 'Predicted_Passengers', 'Lower_Bound', 'Upper_Bound']

output['Predicted_Passengers'] = output['Predicted_Passengers'].round(1)
output['Lower_Bound']          = output['Lower_Bound'].round(1)
output['Upper_Bound']          = output['Upper_Bound'].round(1)

import datetime
future_predictions = output[output['Date'] > '1960-12-01']

output.to_csv('AirPassengers_Forecast_Results.csv', index=False)

print("File saved: AirPassengers_Forecast_Results.csv")
print()
print("Future Predictions (1961 to 1963):")
print(future_predictions.to_string(index=False))

from google.colab import files
files.download('AirPassengers_Forecast_Results.csv')

print()